WITH stadiums AS (
    SELECT UNNEST(ARRAY[
        'Acrisure Stadium',
'Alamo Dome',
'Allegiant Stadium',
'Allianz Arena',
'Alltel Stadium',
'Alumni Stadium',
'Anaheim Stadium',
'Arrowhead Stadium',
'AT&T Stadium',
'Atlanta-Fulton County Stadium',
'Balboa Stadium',
'Bank of America Stadium',
'Bills Stadium',
'Busch Memorial Stadium',
'Caesars Superdome',
'Candlestick Park',
'CenturyLink Field',
'Cinergy Field',
'Cleveland Municipal Stadium',
'Cotton Bowl',
'Cowboys Stadium',
'Dolphin Stadium',
'Edward Jones Dome',
'Empower Field at Mile High',
'Estadio Azteca',
'EverBank Field',
'FedEx Field',
'Fenway Park',
'FirstEnergy Stadium',
'Ford Field',
'Foxboro Stadium',
'Franklin Field',
'GEHA Field at Arrowhead Stadium',
'Georgia Dome',
'Giants Stadium',
'Gillette Stadium',
'Hard Rock Stadium',
'Harvard Stadium',
'Heinz Field',
'Highmark Stadium',
'Houlihan''s Stadium',
'Houston Astrodome',
'Hubert H. Humphrey Metrodome',
'Husky Stadium',
'Jack Murphy Stadium',
'Joe Robbie Stadium',
'Kansas City Municipal Stadium',
'Kezar Stadium',
'Lambeau Field',
'Legion Field',
'Levi''s Stadium',
'Liberty Bowl Memorial Stadium',
'Lincoln Financial Field',
'Los Angeles Memorial Coliseum',
'Louisiana Superdome',
'LP Stadium',
'Lucas Oil Stadium',
'Lumen Field',
'M&T Bank Stadium',
'Mall of America Field',
'Memorial Stadium (Baltimore)',
'Memorial Stadium (Champaign)',
'Memorial Stadium (Clemson)',
'Mercedes-Benz Stadium',
'Mercedes-Benz Superdome',
'MetLife Stadium',
'Metropolitan Stadium',
'Mile High Stadium',
'New Era Field',
'Nippert Stadium',
'Nissan Stadium',
'NRG Stadium',
'Oakland Coliseum',
'Orange Bowl',
'Paul Brown Stadium',
'Paycor Stadium',
'Pitt Stadium',
'Pontiac Silverdome',
'Pro Player Stadium',
'Qualcomm Stadium',
'Ralph Wilson Stadium',
'Raymond James Stadium',
'RCA Dome',
'Reliant Stadium',
'RFK Memorial Stadium',
'Rice Stadium',
'Rogers Centre',
'Rose Bowl',
'Seattle Kingdome',
'Shea Stadium',
'SoFi Stadium',
'Soldier Field',
'Sports Authority Field at Mile High',
'Stanford Stadium',
'State Farm Stadium',
'StubHub Center',
'Sun Devil Stadium',
'Sun Life Stadium',
'Tampa Stadium',
'TCF Bank Stadium',
'Texas Stadium',
'Three Rivers Stadium',
'TIAA Bank Field',
'Tiger Stadium',
'Tiger Stadium (LSU)',
'Tottenham Hotspur Stadium',
'Tottenham Stadium',
'Tulane Stadium',
'Twickenham Stadium',
'U.S. Bank Stadium',
'University of Phoenix Stadium',
'Vanderbilt Stadium',
'Veterans Stadium',
'War Memorial Stadium',
'Wembley Stadium',
'Wrigley Field',
'Yale Bowl',
'Yankee Stadium']) AS stadium_name
)
SELECT *
FROM nfl_stadium
WHERE stadium_name not IN (SELECT stadium_name FROM stadiums);